// <auto-generated />
namespace HInfrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AlterandoTarefa : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlterandoTarefa));
        
        string IMigrationMetadata.Id
        {
            get { return "201609071123116_AlterandoTarefa"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
